name: Yoda Nehoda
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24367
title: Infosec Republic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f5f1'
    - '#343537'
    - '#0b0e13'
    - '#94959a'
    - '#87b5e8'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
