typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#502158'
    - '#786d8d'
    - '#145857'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Yoda Nehoda
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Geek Shit
    id: 0fa951a6-42a0-421f-ae77-4643d73d6b73
    type: content
favicon: null
title: 'Telling it like is all the time '
purpose: []
