name: Yoda Nehoda
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Learn the Force You Will
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#502158'
    - '#786d8d'
    - '#145857'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
