name: Yoda Nehoda
favicon: null
layout_spectrum: 0.48397
typography_spectrum: 0.24367
title: Learn the Force You Will
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000100'
    - '#443425'
    - '#6c6e69'
    - '#a5bbc6'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
